// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: game.proto

#include "game.pb.h"
#include "game.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace game {

static const char* lobby_method_names[] = {
  "/game.lobby/Login",
  "/game.lobby/Register",
  "/game.lobby/FindGame",
};

std::unique_ptr< lobby::Stub> lobby::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< lobby::Stub> stub(new lobby::Stub(channel, options));
  return stub;
}

lobby::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Login_(lobby_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Register_(lobby_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_FindGame_(lobby_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status lobby::Stub::Login(::grpc::ClientContext* context, const ::game::login_request& request, ::game::login_response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::game::login_request, ::game::login_response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Login_, context, request, response);
}

void lobby::Stub::async::Login(::grpc::ClientContext* context, const ::game::login_request* request, ::game::login_response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::game::login_request, ::game::login_response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, std::move(f));
}

void lobby::Stub::async::Login(::grpc::ClientContext* context, const ::game::login_request* request, ::game::login_response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::game::login_response>* lobby::Stub::PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::game::login_request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::game::login_response, ::game::login_request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Login_, context, request);
}

::grpc::ClientAsyncResponseReader< ::game::login_response>* lobby::Stub::AsyncLoginRaw(::grpc::ClientContext* context, const ::game::login_request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLoginRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status lobby::Stub::Register(::grpc::ClientContext* context, const ::game::register_request& request, ::game::register_response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::game::register_request, ::game::register_response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Register_, context, request, response);
}

void lobby::Stub::async::Register(::grpc::ClientContext* context, const ::game::register_request* request, ::game::register_response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::game::register_request, ::game::register_response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Register_, context, request, response, std::move(f));
}

void lobby::Stub::async::Register(::grpc::ClientContext* context, const ::game::register_request* request, ::game::register_response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Register_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::game::register_response>* lobby::Stub::PrepareAsyncRegisterRaw(::grpc::ClientContext* context, const ::game::register_request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::game::register_response, ::game::register_request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Register_, context, request);
}

::grpc::ClientAsyncResponseReader< ::game::register_response>* lobby::Stub::AsyncRegisterRaw(::grpc::ClientContext* context, const ::game::register_request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRegisterRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status lobby::Stub::FindGame(::grpc::ClientContext* context, const ::game::search_a_game_request& request, ::game::search_a_game_response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::game::search_a_game_request, ::game::search_a_game_response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_FindGame_, context, request, response);
}

void lobby::Stub::async::FindGame(::grpc::ClientContext* context, const ::game::search_a_game_request* request, ::game::search_a_game_response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::game::search_a_game_request, ::game::search_a_game_response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FindGame_, context, request, response, std::move(f));
}

void lobby::Stub::async::FindGame(::grpc::ClientContext* context, const ::game::search_a_game_request* request, ::game::search_a_game_response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FindGame_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::game::search_a_game_response>* lobby::Stub::PrepareAsyncFindGameRaw(::grpc::ClientContext* context, const ::game::search_a_game_request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::game::search_a_game_response, ::game::search_a_game_request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_FindGame_, context, request);
}

::grpc::ClientAsyncResponseReader< ::game::search_a_game_response>* lobby::Stub::AsyncFindGameRaw(::grpc::ClientContext* context, const ::game::search_a_game_request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncFindGameRaw(context, request, cq);
  result->StartCall();
  return result;
}

lobby::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      lobby_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< lobby::Service, ::game::login_request, ::game::login_response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](lobby::Service* service,
             ::grpc::ServerContext* ctx,
             const ::game::login_request* req,
             ::game::login_response* resp) {
               return service->Login(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      lobby_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< lobby::Service, ::game::register_request, ::game::register_response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](lobby::Service* service,
             ::grpc::ServerContext* ctx,
             const ::game::register_request* req,
             ::game::register_response* resp) {
               return service->Register(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      lobby_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< lobby::Service, ::game::search_a_game_request, ::game::search_a_game_response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](lobby::Service* service,
             ::grpc::ServerContext* ctx,
             const ::game::search_a_game_request* req,
             ::game::search_a_game_response* resp) {
               return service->FindGame(ctx, req, resp);
             }, this)));
}

lobby::Service::~Service() {
}

::grpc::Status lobby::Service::Login(::grpc::ServerContext* context, const ::game::login_request* request, ::game::login_response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status lobby::Service::Register(::grpc::ServerContext* context, const ::game::register_request* request, ::game::register_response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status lobby::Service::FindGame(::grpc::ServerContext* context, const ::game::search_a_game_request* request, ::game::search_a_game_response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* game_method_names[] = {
  "/game.game/MakeMove",
};

std::unique_ptr< game::Stub> game::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< game::Stub> stub(new game::Stub(channel, options));
  return stub;
}

game::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_MakeMove_(game_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status game::Stub::MakeMove(::grpc::ClientContext* context, const ::game::make_move_request& request, ::game::make_move_response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::game::make_move_request, ::game::make_move_response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_MakeMove_, context, request, response);
}

void game::Stub::async::MakeMove(::grpc::ClientContext* context, const ::game::make_move_request* request, ::game::make_move_response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::game::make_move_request, ::game::make_move_response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MakeMove_, context, request, response, std::move(f));
}

void game::Stub::async::MakeMove(::grpc::ClientContext* context, const ::game::make_move_request* request, ::game::make_move_response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MakeMove_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::game::make_move_response>* game::Stub::PrepareAsyncMakeMoveRaw(::grpc::ClientContext* context, const ::game::make_move_request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::game::make_move_response, ::game::make_move_request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_MakeMove_, context, request);
}

::grpc::ClientAsyncResponseReader< ::game::make_move_response>* game::Stub::AsyncMakeMoveRaw(::grpc::ClientContext* context, const ::game::make_move_request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncMakeMoveRaw(context, request, cq);
  result->StartCall();
  return result;
}

game::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      game_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< game::Service, ::game::make_move_request, ::game::make_move_response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](game::Service* service,
             ::grpc::ServerContext* ctx,
             const ::game::make_move_request* req,
             ::game::make_move_response* resp) {
               return service->MakeMove(ctx, req, resp);
             }, this)));
}

game::Service::~Service() {
}

::grpc::Status game::Service::MakeMove(::grpc::ServerContext* context, const ::game::make_move_request* request, ::game::make_move_response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace game

